name: test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          env > test.txt
          
      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: |
            test.txt
